### ISSUE TITLE
Error 40102: Invalid integration key in request credentials at duo_verify.pl line 31

### ISSUE THREAD

**Issue by harikrishnanp** [duosecurity/duo_api_perl#1]
I'm getting this error when I run `perl duo_verify.pl integration_key secret_key integration_host E.164-formatted_phone_number`

`Error 40102: Invalid integration key in request credentials at duo_verify.pl line 31.`

But I'm using correct keys.

**Comment by BradleyHiggins** [comment]
The integration key you originally posted is for the Auth API, and won't work for Verify API calls.  

If you would like access to the Verify API, please contact Duo with your request.  See https://www.duosecurity.com/docs/duoverify for more information.

It also appears that you have accidentally exposed your skey for this integration in your original comment.  You can change your skey by accessing your admin panel, select 'Applications', then select your Auth API applicaiton, and finally click 'Reset secret key.'  You'll also have to update whatever code you have that was using your old secret key.

Thanks for using Duo!
